name: CI

on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master
jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        repo: ['DBM-Retail']

    steps:

      - name: Deploy on ${{ matrix.repo }}
        run: |
          COMMIT_MESSAGE=$(echo '${{ github.event.head_commit.message}}' | sed 's/"/\\"/g')
          echo $COMMIT_MESSAGE
          cd /home/runner/work/DBM-Unified/${{ matrix.repo }}
          git remote set-url origin "https://${{ secrets.PERSONAL_TOKEN }}@github.com/DeadlyBossMods/${{ matrix.repo }}.git"
          git config user.email "${{ github.event.head_commit.author.email }}"
          git config user.name "${{ github.event.head_commit.author.username }}"
          git commit --allow-empty -m "$COMMIT_MESSAGE"
          git push origin HEAD:master
